---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: hayzedak/cartservice:latest
        ports:
        - containerPort: 7070
        env:
        - name: ASPNETCORE_HTTP_PORTS
          value: "7070"
        - name: DOTNET_EnableDiagnostics
          value: "0"
        - name: REDIS_HOST
          value: redis
      volumes:
      - name: redis-data
        emptyDir: {}
      # restartPolicy: Unless-stopped
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  selector:
    app: cartservice
  ports:
  - port: 7070
    targetPort: 7070