---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: hayzedak/loadgenerator:latest
        env:
        - name: FRONTEND_ADDR
          value: frontend:8080
        - name: USERS
          value: "10"
      # restartPolicy: Unless-stopped
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
spec:
  selector:
     app: loadgenerator
  ports:
    - port: 80           # Dummy port to satisfy the Service spec requirement
      targetPort: 8080    # Target port, can be any unused port since loadgenerator doesn't need on
      #protocol: TCP
     # type: ClusterIP         # Keeps the service internal to the Kubernetes cluster

