---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: hayzedak/loadgenerator:latest
        env:
        - name: FRONTEND_ADDR
          value: frontend:8080
        - name: USERS
          value: "10"
      # restartPolicy: Unless-stopped
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
spec:
  selector:
    app: loadgenerator