---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: hayzedak/shippingservice:latest
        ports:
        - containerPort: 50051
        env:
        - name: APP_PORT
          value: "50051"
        - name: GOTRACEBACK
          value: single
      # restartPolicy: Unless-stopped
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app: shippingservice
  ports:
  - port: 50051
    targetPort: 50051