name: Microservices Demo Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

env:
  DOCKER_HUB_USERNAME: 'hayzedak'
  SERVICE_NAME: 'adservice'
  SERVICE_PATH: './src/adservice'
  SONAR_SCANNER_VERSION: '6.2' 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # Run SonarQube analysis (using official SonarSource scanner)
      - name: SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@v1.1.0  # Changed this line
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_AUTH_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=microservices-demo-adservice
            -Dsonar.projectName='Microservices adservice'
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=${{ env.SERVICE_PATH }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:${{ github.sha }} $SERVICE_PATH

      # Run Trivy Security Scan
      - name: Run Trivy Security Scan
        env:
          DOCKER_IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull aquasec/trivy:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image \
            ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:${DOCKER_IMAGE_TAG} --severity HIGH,CRITICAL

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:${{ github.sha }}
          docker tag ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:${{ github.sha }} ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:latest
          docker push ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:latest

      - name: Clean up Workspace
        run: |
          rm -rf $SERVICE_PATH