name: Microservices Demo Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

env:
  DOCKER_HUB_USERNAME: 'hayzedak'
  SERVICE_NAME: 'adservice'
  SERVICE_PATH: './src/adservice'
  SONAR_SCANNER_VERSION: '6.2' 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Download and install SonarScanner version 6.2
      - name: Download and install SonarScanner 6.2
        run: |
          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
          unzip sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip -d $HOME/sonar-scanner
          echo "SONAR_SCANNER_HOME=$HOME/sonar-scanner/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}" >> $GITHUB_ENV

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:${{ github.sha }} $SERVICE_PATH

      # Run SonarQube analysis
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_AUTH_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Using SONAR_HOST_URL secret for the SonarQube server URL
        run: |
          $SONAR_SCANNER_HOME/bin/sonar-scanner \
            -Dsonar.projectKey=microservices-demo-adservice \
            -Dsonar.projectName="Microservices adservice" \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=$SERVICE_PATH \
            -Dsonar.java.binaries=$SERVICE_PATH/target/classes \
            -Dsonar.junit.reportPaths=$SERVICE_PATH/target/surefire-reports \
            -Dsonar.coverage.jacoco.xmlReportPaths=$SERVICE_PATH/target/site/jacoco/jacoco.xml \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # Run Trivy Security Scan
      - name: Run Trivy Security Scan
        env:
          DOCKER_IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull aquasec/trivy:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image \
            ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:${DOCKER_IMAGE_TAG} --severity HIGH,CRITICAL

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:${{ github.sha }}
          docker tag ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:${{ github.sha }} ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:latest
          docker push ${DOCKER_HUB_USERNAME}/${SERVICE_NAME}:latest

      - name: Clean up Workspace
        run: |
          rm -rf $SERVICE_PATH
